name: Integration tests Python2

on:
  pull_request:
    branches:
     - master
  push:
    branches:
      - master

jobs:
  tests:
    runs-on: ubuntu-20.04
    if: "!contains(github.event.pull_request.labels.*.name, 'disable-integration-tests')"
    steps:
    - uses: actions/checkout@v2
    - name: Install Python2.7
      uses: actions/setup-python@v4
      with:
        python-version: 2.7

    - name: Test with pytest
      run: |
        ./ci/run_integration_test.sh tests/integration/
